* Introduction
Prerequisites:
+ [[https://nodejs.org/en/][Node.js]] installed (at least version 8 recommended)

We use the architecture described [[https://github.com/mqtt-smarthome/mqtt-smarthome/blob/master/Architecture.md][here]].
* MQTT broker
** local installation
We use [[https://github.com/mcollina/mosca][mosca]].

Install it:
#+BEGIN_SRC sh
npm install -g mosca 
#+END_SRC

Run it:
#+BEGIN_SRC sh
mosca -v
#+END_SRC

** use cloud service
We can use a free plan (Cute Cat) of [[https://www.cloudmqtt.com/plans.html][CloudMQTT]]. Note that traffic to and from the broker in the cloud will not be encrypted (due to missing SSL support).

You can either create an account or sign in with an existing GitHub or Google account.

1. Enter a name for your instance.
2. Make sure to select the "Cute Cat" free plan.
3. Select a data center. Note that US-East may have a higher load than other regions.
4. On the instance details, you will find all details needed to connect:
   + server
   + port
   + user
   + password

* Node RED

** Installation and startup
Install it:
#+BEGIN_SRC sh
npm install -g node-red
#+END_SRC

Start it:
#+BEGIN_SRC sh
node-red
#+END_SRC

The output should include a line like
#+BEGIN_QUOTE
26 Oct 10:57:14 - [info] Server now running at http://127.0.0.1:1880/
#+END_QUOTE

Open a browser at this URL.

** Sending a message to the broker
Use drag and drop to add an
+ "inject" /input/ node
+ "mqtt" /output/ node
to the current flow.

Connect them, and double click the mqtt node to configure your MQTT broker. Edit the "Server" property and set the server and port.
+ for the local mosca broker, use "localhost" for the server and 1883 for the port.
+ for the cloud broker, use the server, port, user and password informations listed on the instance details. User and password can be entered on the "Security" tab.

Set the "Topic" property.

Confirm your input, and click the /Deploy/ button in the upper right corner.

By clicking on the button at the left side of the inject node, you can send a message to the broker.

** Receiving messages from the broker
Use drag and drop to add an
+ "mqtt" /input/ node
+ "debug" /output/ node
to the current flow.

Connect them, and check that the mqtt input node uses the same server as the mqtt output node we added previously. Set the "Topic" property to the same value, too.

In the right pane, replace the "info" view with the "debug" view by clicking on the "bug" button.

Click /Deploy/ again, and send a message with the inject node from the previous step. You should now see the message in the debug pane.

You can disable your debug output by clicking the button to the right of the debug node.

* Micro Controller: MQTT gateway
