esphome:
  on_boot:
    - lambda: 'ESP.eraseConfig();'
  name: radio_transceiver
  platform: ESP8266
  board: nodemcuv2
  includes:
    - cc1101_component.h
    - libraries/SmartRC-CC1101-Driver-Lib/ELECHOUSE_CC1101_SRC_DRV.cpp
    - libraries/SmartRC-CC1101-Driver-Lib/ELECHOUSE_CC1101_SRC_DRV.h
    - libraries/radio/radio.h
    - libraries/radio/radio.cpp
  libraries:
    - SPI

wifi:
  ssid: WIFI_SSID           # enter your wifi ssid
  password: WIFI_PASSWORD   # enter your wifi password
  fast_connect: True

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:

ota:

mqtt:
  broker: 192.168.0.X    # change to your local ip address
  # client_id:      for remote mqtt broker
  # username:       for remote mqtt broker
  # password:       for remote mqtt broker

custom_component:
  # configure topics, repetitions and delay
  - lambda: |-
      char const *send_rf_topic = "radio_transceiver/radio/MQTTto433";
      char const *receive_rf_topic = "radio_transceiver/radio/433toMQTT";
      int send_repetitions = 5;
      int delay_between_send = 300;
      auto cc1101 = new CC1101Component(send_rf_topic, receive_rf_topic, send_repetitions, delay_between_send);
      return {cc1101};
